# Generated by Django 4.1.5 on 2023-01-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_name', models.CharField(blank=True, max_length=150, null=True)),
                ('camp_status', models.BooleanField()),
                ('trigger_type', models.CharField(blank=True, max_length=125, null=True)),
                ('trigger_value', models.JSONField(blank=True)),
                ('sending_window_days', models.CharField(blank=True, max_length=125, null=True)),
                ('sending_window_starttime', models.CharField(blank=True, max_length=20, null=True)),
                ('sending_window_endtime', models.CharField(blank=True, max_length=20, null=True)),
                ('sending_window_status', models.BooleanField()),
                ('send_number_number', models.CharField(blank=True, max_length=10)),
                ('double_optin_keyword', models.CharField(max_length=150, null=True)),
                ('double_optin_message', models.CharField(blank=True, max_length=250, null=True)),
                ('double_optin_status', models.BooleanField()),
                ('limit_multiple_messasge', models.CharField(blank=True, max_length=200, null=True)),
                ('limit_multiple_status', models.BooleanField()),
                ('cancellation_on_reply', models.BooleanField()),
                ('cancellation_status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='campaign_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=150, null=True)),
                ('action_value', models.JSONField(blank=True)),
                ('oreder', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.campaign')),
            ],
        ),
    ]
